CREATE TABLE MEMBER (
    M_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    M_NAME VARCHAR(20),
    M_GENDER VARCHAR(6),
    M_BIRTH VARCHAR(8)
);



insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Klimkovich', 'Male', '19830508');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Daenen', 'Female', '19991114');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Darkin', 'Male', '19790217');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Bevis', 'Female', '19770812');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Shellcross', 'Female', '20110304');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Baudi', 'Male', '20060831');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Edmand', 'Female', '20090813');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Czapla', 'Male', '19841111');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Brolechan', 'Female', '20160907');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Haycroft', 'Female', '19950723');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Yole', 'Female', '19731110');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Rickwood', 'Female', '19850819');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Deave', 'Male', '19930210');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Baudic', 'Female', '19950318');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Jarrold', 'Male', '19871117');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Danielski', 'Male', '20010118');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Boulds', 'Male', '20200915');
insert into MEMBER (M_NAME, M_GENDER, M_BIRTH) values ('Cowely', 'Female', '20030625');


INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;
INSERT INTO MEMBER (M_NAME, M_GENDER, M_BIRTH) SELECT M_NAME, M_GENDER, M_BIRTH FROM MEMBER;




/**
SELECT COUNT(*) FROM MEMBER;

SELECT (SELECT COUNT(M_GENDER) FROM MEMBER WHERE M_GENDER='Male') AS MALE, (SELECT COUNT(M_GENDER) FROM MEMBER WHERE M_GENDER='Female') AS FEMALE;
**/


/**
ALTER TABLE MEMBER ADD INDEX 'gender' (M_GENDER);

EXPLAIN SELECT * FROM (SELECT M_GENDER AS GENDER, COUNT(M_GENDER) AS COUNT FROM MEMBER GROUP BY M_GENDER ORDER BY M_GENDER) AS M ORDER BY GENDER;
**/
/**
CREATE TABLE MEMBER_GENDER(
    MG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    MG_MALE INT NOT NULL,
    MG_FEMALE INT NOT NULL
);

INSERT INTO MEMBER_GENDER (MG_MALE, MG_FEMALE) SELECT (SELECT COUNT(M_GENDER) FROM MEMBER WHERE M_GENDER='Male') AS Male, (SELECT COUNT(M_GENDER) FROM MEMBER WHERE M_GENDER='Female') AS Female;


SELECT MG_MALE AS MALE, MG_FEMALE AS FEMALE FROM MEMBER_GENDER;

CREATE EVENT IF NOT EXISTS MEMBER_GENDER_SCHEDULER
    ON SCHEDULE EVERY 1 Day
    -- STARTS '2022-01-01 03:00:00'
    COMMENT '회원의 성별 집계'
DO
UPDATE MEMBER_GENDER SET MG_MALE = (SELECT COUNT(M_GENDER) FROM MEMBER WHERE M_GENDER='Male'), MG_FEMALE = (SELECT COUNT(M_GENDER) FROM MEMBER WHERE M_GENDER='Female') WHERE MG_ID = 1;
**/

ALTER TABLE MEMBER ADD INDEX `birth` (M_BIRTH);


SELECT (YEAR(NOW()) - LEFT(M_BIRTH, 4) + 1) AS AGE, COUNT(*) AS COUNT FROM MEMBER GROUP BY AGE ORDER BY AGE ASC;

CREATE TABLE MEMBER_BIRTH(
    MG_AGE INT NOT NULL PRIMARY KEY,
    MG_COUNT INT NOT NULL
);

INSERT INTO MEMBER_BIRTH(MG_AGE, MG_COUNT) SELECT (YEAR(NOW()) - LEFT(M_BIRTH,4) + 1) AS AGE, COUNT(*) AS COUNT FROM MEMBER GROUP BY AGE ORDER BY AGE ASC;

EXPLAIN SELECT MG_AGE AS AGE, MG_COUNT AS COUNT FROM MEMBER_BIRTH;



SELECT * FROM (SELECT (YEAR(NOW()) - LEFT(M_BIRTH, 4) + 1) AS AGE, COUNT(*) AS COUNT FROM MEMBER GROUP BY AGE) AS M ORDER BY AGE ASC;


CREATE EVENT IF NOT EXISTS MEMBER_BIRTH_SCHEDULER
    ON SCHEDULE EVERY 1 Day
    -- STARTS '2022-01-01 03:00:00'
    COMMENT '회원의 나이 집계'
DO
INSERT INTO MEMBER_BIRTH (MG_AGE, MG_COUNT) SELECT AGE, COUNT FROM (SELECT (YEAR(NOW()) - LEFT(M_BIRTH, 4) + 1) AS AGE, COUNT(*) FROM MEMBER GROUP BY AGE) AS M ON DUPLICATE KEY UPDATE MG_AGE = M.AGE, MG_COUNT = M.COUNT;